version: '3.9'
networks:
  crud-net:
    name: crud-net
services:
  crud-db:
    container_name: crud-db
    hostname: crud-db
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crud
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    working_dir: /var/lib/mysql
    volumes:
      # - ./apps/mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - crud-net
  crud-api:
    container_name: crud-api
    hostname: crud-api
    image: crud/api
    restart: unless-stopped
    build: ./api
    ports:
      - "3001:3001"
    networks:
      - crud-net
    depends_on:
      - crud-db
  crud-web:
    container_name: crud-web
    hostname: crud-web
    image: crud/web
    restart: unless-stopped
    build: ./web
    ports:
      - "3000:3000"
    networks:
      - crud-net
    depends_on:
      - crud-db
  adminer:
    container_name: adminer
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: mysql
    networks:
    - crud-net
