---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb
data:
  db_init.sql: |
    CREATE TABLE items (
        id MEDIUMINT NOT NULL AUTO_INCREMENT,
        ITEM VARCHAR(30) NOT NULL,
        PRIMARY KEY (id)
    );
