name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [runner1]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Nada
      run: echo Hello!!!
      
#   build2:
#     runs-on: [self-hosted, runner2]
#     steps:
#     - uses: actions/checkout@v2
#     - name: Nada
#       run: echo Hello!!!
